### ISSUE TITLE
- Research hyperledger fabric 1.2 and compare with 1.1:

### ISSUE THREAD

**Issue by datlv** [deevotech/sc-network.deevo.io#1]
- functions
   - modules
   - components
- Combine hyperledger fabric 1.2 with bftsmart ordering service
- Research system chaincode to run with supply chain system

**Comment by quangpq** [comment]
Report: [Hyperledger Fabric BFTSmart Version 1.2](https://docs.google.com/document/d/17NbGUae_I3WG5TB0s2cj-rzuoTrxkudl1JrMP_a4JvA)
